# Generated by Django 4.2.23 on 2026-06-09 14:39

from django.db import migrations, models

from core.slug_backfill import backfill_slugs


def backfill(apps, schema_editor):
    backfill_slugs(apps.get_model('miro', 'Board'), source_field='title')


class Migration(migrations.Migration):

    dependencies = [
        ('miro', '0004_rename_miro_boarda_user_id_7fb95b_idx_miro_boarda_user_id_e19366_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='board',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
