# Generated by Django 4.2.23 on 2026-05-09 13:30

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('budget_approval', '0004_add_budget_pool_name'),
    ]

    operations = []
