# Generated by Django 4.2.23 on 2026-05-12 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget_approval', '0005_add_cancelled_status_to_budget_request'),
    ]

    operations = []
