# Generated by Django for MED-328.

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AuthenticationLockout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('ip', 'IP address'), ('username', 'Username')], max_length=20)),
                ('identifier', models.CharField(db_index=True, max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(db_index=True)),
                ('last_attempt_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'authentication_lockouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='authenticationlockout',
            index=models.Index(fields=['scope', 'identifier', 'locked_until'], name='authenticat_scope_b7a054_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationlockout',
            index=models.Index(fields=['scope', 'identifier', 'resolved_at'], name='authenticat_scope_125690_idx'),
        ),
    ]
