# Generated by Django 4.2.23 on 2026-06-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_meta', '0002_fix_free_sentinel_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='base_price_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='extra_seat_price_cents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='included_seats',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_tokens_per_call',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='monthly_token_quota',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='overage_price_cents_per_1m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_extra_seat_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_overage_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='monthly_revenue_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='seat_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_overage_item_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_previews_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_tasks_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_team_members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_internal', False)), fields=('organization',), name='unique_active_real_subscription_per_org'),
        ),
    ]
