# Generated by Django 4.2.23 on 2026-06-07 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_org_stripe_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0017_remove_agentworkflowrun_user_context'),
        ('stripe_meta', '0004_seed_token_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=7)),
                ('tokens_used', models.BigIntegerField(default=0)),
                ('tokens_reserved', models.BigIntegerField(default=0)),
                ('overage_tokens', models.BigIntegerField(default=0)),
                ('overage_reported_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'unique_together': {('organization', 'year_month')},
            },
        ),
        migrations.CreateModel(
            name='OrgMonthlyCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=7)),
                ('llm_cost_cents', models.IntegerField(default=0)),
                ('total_tokens', models.BigIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'unique_together': {('organization', 'year_month')},
            },
        ),
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=80)),
                ('input_tokens', models.IntegerField()),
                ('output_tokens', models.IntegerField()),
                ('normalized_tokens', models.BigIntegerField()),
                ('input_cost_cents', models.IntegerField()),
                ('output_cost_cents', models.IntegerField()),
                ('total_cost_cents', models.IntegerField()),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.agentsession')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'created_at'], name='stripe_meta_organiz_1d00b5_idx')],
            },
        ),
    ]
