# Generated by Django 4.2.23 on 2026-06-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_meta', '0007_backfill_seat_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='AUD', max_length=3),
        ),
    ]
