# Generated by Django 4.2.23 on 2026-06-12 01:34

from django.db import migrations, models


def backfill_reported_tokens(apps, schema_editor):
    """
    Rows already reported under the legacy floor scheme (overage_reported_at set)
    were billed floor(overage_tokens / 1M) units. Credit exactly that amount so
    the new delta-based reporter does not re-bill them.
    """
    UsageMonthly = apps.get_model('stripe_meta', 'UsageMonthly')
    for row in UsageMonthly.objects.filter(overage_reported_at__isnull=False):
        row.overage_reported_tokens = (row.overage_tokens // 1_000_000) * 1_000_000
        row.save(update_fields=['overage_reported_tokens'])


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_meta', '0009_subscription_cancel_at_period_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagemonthly',
            name='overage_reported_tokens',
            field=models.BigIntegerField(default=0),
        ),
        migrations.RunPython(backfill_reported_tokens, migrations.RunPython.noop),
    ]
