# Generated by Django 4.2.23 on 2026-06-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_meta', '0010_usagemonthly_overage_reported_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripewebhookevent',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
