# Generated by Django 4.2.23 on 2026-06-03 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import notifications.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(default=notifications.models.default_notification_preferences)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('COLLABORATION', 'Collaboration'), ('MEETINGS', 'Meetings'), ('TASKS', 'Tasks'), ('DECISIONS', 'Decisions'), ('APPROVAL', 'Approval'), ('SYSTEM', 'System'), ('AUTOMATION', 'Automation'), ('INTEGRATIONS', 'Integrations')], db_index=True, max_length=32)),
                ('event_type', models.CharField(choices=[('chat_new_message', 'Chat new message'), ('chat_new_conversation', 'Chat new conversation'), ('message_reminder', 'Message reminder'), ('project_invite', 'Project invitation'), ('calendar_reminder', 'Calendar reminder'), ('doc_asset_update', 'Document or asset update'), ('meeting_created', 'Meeting created'), ('meeting_updated', 'Meeting updated'), ('meeting_participant_added', 'Added to meeting'), ('meeting_participant_removed', 'Removed from meeting'), ('meeting_starting_soon', 'Meeting starting soon'), ('meeting_agenda_changed', 'Agenda changed'), ('meeting_minutes_published', 'Minutes published'), ('task_assigned', 'Task assigned'), ('task_owner_changed', 'Task owner changed'), ('task_status_changed', 'Task status changed'), ('task_deadline_soon', 'Deadline approaching'), ('task_overdue', 'Task overdue'), ('task_comment_mention', 'Mentioned in comment'), ('task_anomaly', 'Task anomaly alert'), ('decision_review_needed', 'Decision needs review'), ('decision_deadline', 'Decision deadline'), ('decision_published', 'Decision published'), ('budget_review_needed', 'Budget needs review'), ('budget_approval_result', 'Budget approval result'), ('budget_pool_low', 'Budget pool insufficient'), ('budget_escalation', 'Budget escalation'), ('workflow_node', 'Workflow node update'), ('account_permission', 'Account permission changed'), ('billing_anomaly', 'Billing anomaly'), ('system', 'System')], db_index=True, max_length=64)),
                ('related_object_type', models.CharField(blank=True, default='', max_length=64)),
                ('related_object_id', models.CharField(blank=True, default='', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('action_url', models.CharField(blank=True, default='', max_length=1024)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('responded', models.BooleanField(db_index=True, default=False)),
                ('response', models.CharField(blank=True, choices=[('accept', 'Accepted'), ('reject', 'Rejected')], default='', max_length=16)),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered the event; used to suppress self-notifications.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_triggered', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('chat_new_message', 'Chat new message'), ('chat_new_conversation', 'Chat new conversation'), ('message_reminder', 'Message reminder'), ('project_invite', 'Project invitation'), ('calendar_reminder', 'Calendar reminder'), ('doc_asset_update', 'Document or asset update'), ('meeting_created', 'Meeting created'), ('meeting_updated', 'Meeting updated'), ('meeting_participant_added', 'Added to meeting'), ('meeting_participant_removed', 'Removed from meeting'), ('meeting_starting_soon', 'Meeting starting soon'), ('meeting_agenda_changed', 'Agenda changed'), ('meeting_minutes_published', 'Minutes published'), ('task_assigned', 'Task assigned'), ('task_owner_changed', 'Task owner changed'), ('task_status_changed', 'Task status changed'), ('task_deadline_soon', 'Deadline approaching'), ('task_overdue', 'Task overdue'), ('task_comment_mention', 'Mentioned in comment'), ('chat_mention', 'Mentioned in chat'), ('chat_thread_reply', 'Reply in thread'), ('chat_reaction', 'Reaction to your message'), ('task_anomaly', 'Task anomaly alert'), ('decision_review_needed', 'Decision needs review'), ('decision_deadline', 'Decision deadline'), ('decision_published', 'Decision published'), ('budget_review_needed', 'Budget needs review'), ('budget_approval_result', 'Budget approval result'), ('budget_pool_low', 'Budget pool insufficient'), ('budget_escalation', 'Budget escalation'), ('workflow_node', 'Workflow node update'), ('account_permission', 'Account permission changed'), ('billing_anomaly', 'Billing anomaly'), ('system', 'System')], db_index=True, max_length=64),
        ),
    ]
