# Generated by Django 4.2.23 on 2026-05-13 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import notifications.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0004_notification_responded'),
    ]

    operations = []
