# Generated by Django 4.2.23 on 2026-05-13 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import notifications.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0004_notification_responded'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_a972ce_idx',
            old_name='notificatio_recipie_0f8a2d_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_4e3567_idx',
            old_name='notificatio_recipie_6f1a9c_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='User who triggered the event; used to suppress self-notifications.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_triggered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usernotificationpreference',
            name='preferences',
            field=models.JSONField(default=notifications.models.default_notification_preferences),
        ),
    ]
