# Generated by Django 4.2.23 on 2026-05-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_budget_notification_events'),
    ]

    operations = []
