# Generated by Django 4.2.23 on 2026-06-03 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinearCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linear_workspace_key', models.CharField(blank=True, db_column='organization_id', default='', help_text='Legacy varchar column; MediaJira org id as string and/or future Linear workspace id.', max_length=64)),
                ('organization_name', models.CharField(blank=True, default='', help_text='Denormalized org name for display.', max_length=255)),
                ('default_team_id', models.CharField(blank=True, default='', max_length=64)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('encrypted_access_token', models.TextField()),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinearTaskLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linear_issue_id', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'linear_integration_lineartasklink',
            },
        ),
        migrations.AddField(
            model_name='lineartasklink',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linear_links', to='task.task'),
        ),
        migrations.AddField(
            model_name='linearcredential',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linear_credential', to=settings.AUTH_USER_MODEL),
        ),
    ]
