# Generated by Django 4.2.23 on 2026-06-03 12:01

import chat.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.contrib.postgres.indexes
import django.contrib.postgres.search


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('private', 'Private Chat'), ('group', 'Group Chat')], default='private', help_text='Type of chat: private (1-on-1) or group', max_length=20)),
                ('name', models.CharField(blank=True, help_text='Name for group chats (optional for private chats)', max_length=200, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='When the user joined this chat')),
                ('last_read_at', models.DateTimeField(blank=True, help_text='Last time the user read messages in this chat (for quick unread count)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this user is still active in the chat')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0, help_text='Order within starred list for this user in the chat project')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, default='', help_text='Text content of the message')),
                ('has_attachments', models.BooleanField(default=False, help_text='Whether this message has attachments (for optimization)')),
                ('forwarded_from_sender_display', models.CharField(blank=True, help_text='Snapshot of original sender display name at forward time', max_length=255, null=True)),
                ('forwarded_from_created_at', models.DateTimeField(blank=True, help_text='Snapshot of original message creation time at forward time', null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When the message was soft deleted', null=True)),
                ('is_revoked', models.BooleanField(default=False, help_text='Whether the message has been revoked by sender')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When the message was revoked', null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('file', models.FileField(help_text='The uploaded file', upload_to=chat.models.temp_attachment_upload_path)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='document', help_text='Type of attachment: image, video, or document', max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('original_filename', models.CharField(help_text='Original filename as uploaded', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', help_text='MIME type of the file', max_length=100)),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail for images and videos', null=True, upload_to='chat/thumbnails/')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('emoji', models.CharField(help_text='Emoji character (e.g., 😊, 👍)', max_length=10)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('remind_at', models.DateTimeField(help_text='When to send the reminder notification')),
                ('note', models.CharField(blank=True, default='', help_text='Optional note for the reminder', max_length=255)),
                ('is_sent', models.BooleanField(default=False, help_text='Whether the reminder notification has been sent')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the reminder notification was sent', null=True)),
            ],
            options={
                'ordering': ['remind_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', help_text='Current status of the message for this user', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the message was delivered to the user', null=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='When the user read the message', null=True)),
                ('message', models.ForeignKey(help_text='The message this status refers to', on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='chat.message')),
            ],
            options={
                'verbose_name_plural': 'Message statuses',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='messagestatus',
            name='user',
            field=models.ForeignKey(help_text='The recipient user', on_delete=django.db.models.deletion.CASCADE, related_name='message_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagereminder',
            name='message',
            field=models.ForeignKey(help_text='The message to be reminded about', on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='chat.message'),
        ),
        migrations.AddField(
            model_name='messagereminder',
            name='user',
            field=models.ForeignKey(help_text='User who set the reminder', on_delete=django.db.models.deletion.CASCADE, related_name='message_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='message',
            field=models.ForeignKey(help_text='The message this reaction is on', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.message'),
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='user',
            field=models.ForeignKey(help_text='User who reacted', on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='message',
            field=models.ForeignKey(blank=True, help_text='The message this attachment belongs to (null for temp uploads)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message'),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='uploader',
            field=models.ForeignKey(help_text='User who uploaded this attachment', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat'),
        ),
        migrations.AddField(
            model_name='message',
            name='forwarded_from_message',
            field=models.ForeignKey(blank=True, help_text='Original message that this message was forwarded from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_messages', to='chat.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='hidden_by_users',
            field=models.ManyToManyField(blank=True, help_text='Users who have hidden this message (personal hide, not affecting others)', related_name='hidden_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='Message being replied to (quote reply)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(help_text='User who sent this message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatstar',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='chat.chat'),
        ),
        migrations.AddField(
            model_name='chatstar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_stars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.chat'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='project',
            field=models.ForeignKey(help_text='Project this chat belongs to (required)', on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='core.project'),
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['message', 'status'], name='chat_messag_message_af4e97_idx'),
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['user', 'status'], name='chat_messag_user_id_5081a2_idx'),
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['message', 'user'], name='chat_messag_message_c98ef4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagestatus',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='messagereminder',
            index=models.Index(fields=['is_sent', 'remind_at'], name='chat_messag_is_sent_872aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereminder',
            index=models.Index(fields=['user', 'is_sent'], name='chat_messag_user_id_7ec98c_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereminder',
            index=models.Index(fields=['message', 'user'], name='chat_messag_message_9e6249_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereminder',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['message', 'emoji'], name='chat_messag_message_ce4293_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['user', 'created_at'], name='chat_messag_user_id_e27d94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together={('message', 'user', 'emoji')},
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message', 'created_at'], name='chat_messag_message_a261d7_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['uploader', 'created_at'], name='chat_messag_uploade_c87818_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['file_type'], name='chat_messag_file_ty_820d59_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'created_at'], name='chat_messag_chat_id_0c7b25_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='chat_messag_sender__b02346_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', '-created_at'], name='chat_messag_chat_id_013eed_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'is_deleted'], name='chat_messag_chat_id_a3aeee_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'is_revoked'], name='chat_messag_chat_id_5c9069_idx'),
        ),
        migrations.AddIndex(
            model_name='chatstar',
            index=models.Index(fields=['user', 'position'], name='chat_chatst_user_id_7d6523_idx'),
        ),
        migrations.AddIndex(
            model_name='chatstar',
            index=models.Index(fields=['user', 'chat'], name='chat_chatst_user_id_3839d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatstar',
            unique_together={('user', 'chat')},
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['user', 'is_active'], name='chat_chatpa_user_id_7c5807_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['chat', 'is_active'], name='chat_chatpa_chat_id_38ce59_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatparticipant',
            unique_together={('chat', 'user')},
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['project', '-updated_at'], name='chat_chat_project_a6870a_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['type', '-updated_at'], name='chat_chat_type_4d953f_idx'),
        ),
    
        migrations.CreateModel(
            name='MessageMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PinnedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True, default='', help_text='Plain-text content (mirrors rich_body for search/display)')),
                ('rich_body', models.JSONField(blank=True, help_text='Tiptap JSON document (same format as Message.rich_body)', null=True)),
                ('attachment_ids', models.JSONField(blank=True, default=list, help_text='List of MessageAttachment IDs to link when the message is created')),
                ('mention_ids', models.JSONField(blank=True, default=list, help_text='List of user IDs to @-mention')),
                ('scheduled_at', models.DateTimeField(db_index=True, help_text='When the message should be sent (UTC)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, default='', help_text='Celery task ID — used to revoke the task on cancellation', max_length=255)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error detail if status=failed')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('last_read_at', models.DateTimeField(help_text='Timestamp of the latest thread reply seen by this user.')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this channel (group chats only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Longer description shown in the channel details drawer'),
        ),
        migrations.AddField(
            model_name='chat',
            name='topic',
            field=models.CharField(blank=True, default='', help_text='Short topic line shown in the channel header', max_length=500),
        ),
        migrations.AddField(
            model_name='chat',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public: project members can find and join'), ('member_invite', 'Invite-only: any channel member can add people'), ('manager_invite', 'Restricted: only managers can add people')], default='public', help_text='Who can discover or add members to this channel', max_length=32),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Whether this participant can manage channel members and settings'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='is_muted',
            field=models.BooleanField(default=False, help_text='When True, suppress notifications for this chat for this user'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='muted_until',
            field=models.DateTimeField(blank=True, help_text='Optional expiry time for a temporary mute', null=True),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='notification_level',
            field=models.CharField(choices=[('all', 'All messages'), ('mentions', 'Mentions only'), ('none', 'Nothing')], default='all', help_text='Notification level for this chat', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False, help_text='True after content has been edited'),
        ),
        migrations.AddField(
            model_name='message',
            name='parent_message',
            field=models.ForeignKey(blank=True, help_text='Root message this is a thread reply to. Null = root/main-timeline message.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_replies', to='chat.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='rich_body',
            field=models.JSONField(blank=True, help_text='Tiptap JSON document for rich rendering. content holds the searchable plain-text copy.', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='transcript',
            field=models.TextField(blank=True, default=None, help_text='AI-generated transcript for audio attachments', null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['parent_message', 'created_at'], name='chat_messag_parent__013672_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='chat_msg_search_vec_idx'),
        ),
        migrations.AddField(
            model_name='threadreadstatus',
            name='root_message',
            field=models.ForeignKey(help_text='The parent (root) message whose thread was read.', on_delete=django.db.models.deletion.CASCADE, related_name='thread_read_statuses', to='chat.message'),
        ),
        migrations.AddField(
            model_name='threadreadstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_read_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='chat',
            field=models.ForeignKey(help_text='Chat the message will be sent to', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='chat.chat'),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='Message being quote-replied to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_replies', to='chat.message'),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='sender',
            field=models.ForeignKey(help_text='User who scheduled the message', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='sent_message',
            field=models.ForeignKey(blank=True, help_text='The Message created when this scheduled send fired', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_scheduled', to='chat.message'),
        ),
        migrations.AddField(
            model_name='savedmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='chat.message'),
        ),
        migrations.AddField(
            model_name='savedmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pinnedmessage',
            name='chat',
            field=models.ForeignKey(help_text='Chat channel this pin belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pinned_messages', to='chat.chat'),
        ),
        migrations.AddField(
            model_name='pinnedmessage',
            name='message',
            field=models.ForeignKey(help_text='Message that was pinned', on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='chat.message'),
        ),
        migrations.AddField(
            model_name='pinnedmessage',
            name='pinned_by',
            field=models.ForeignKey(help_text='User who pinned the message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagemention',
            name='mentioned_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_mentions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagemention',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='chat.message'),
        ),
        migrations.AddIndex(
            model_name='threadreadstatus',
            index=models.Index(fields=['user', 'root_message'], name='chat_thread_user_id_d7ca1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='threadreadstatus',
            unique_together={('user', 'root_message')},
        ),
        migrations.AddIndex(
            model_name='scheduledmessage',
            index=models.Index(fields=['sender', 'status', 'scheduled_at'], name='chat_schedu_sender__73be39_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledmessage',
            index=models.Index(fields=['chat', 'status', 'scheduled_at'], name='chat_schedu_chat_id_63099e_idx'),
        ),
        migrations.AddIndex(
            model_name='savedmessage',
            index=models.Index(fields=['user', '-created_at'], name='chat_savedm_user_id_d215d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedmessage',
            unique_together={('user', 'message')},
        ),
        migrations.AddIndex(
            model_name='pinnedmessage',
            index=models.Index(fields=['chat', '-created_at'], name='chat_pinned_chat_id_9ca9c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pinnedmessage',
            unique_together={('chat', 'message')},
        ),
        migrations.AddIndex(
            model_name='messagemention',
            index=models.Index(fields=['mentioned_user', 'created_at'], name='chat_mention_user_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagemention',
            unique_together={('message', 'mentioned_user')},
        ),
    ]
