# Generated by Django 4.2.23 on 2026-05-23 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_add_reply_to_message'),
    ]

    operations = []
