# Generated by Django 4.2.23 on 2026-05-23 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_add_reply_to_message'),
        ('chat', '0006_message_is_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('emoji', models.CharField(help_text='Emoji character (e.g., 😊, 👍)', max_length=10)),
                ('message', models.ForeignKey(help_text='The message this reaction is on', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.message')),
                ('user', models.ForeignKey(help_text='User who reacted', on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['message', 'emoji'], name='chat_messag_message_ce4293_idx'), models.Index(fields=['user', 'created_at'], name='chat_messag_user_id_e27d94_idx')],
                'unique_together': {('message', 'user', 'emoji')},
            },
        ),
    ]
