# Generated by Django 4.2.23 on 2026-05-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_add_message_reminder'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messagereminder',
            new_name='chat_messag_is_sent_872aa0_idx',
            old_name='chat_messag_is_sent_idx',
        ),
        migrations.RenameIndex(
            model_name='messagereminder',
            new_name='chat_messag_user_id_7ec98c_idx',
            old_name='chat_messag_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='messagereminder',
            new_name='chat_messag_message_9e6249_idx',
            old_name='chat_messag_message_idx',
        ),
        migrations.AddField(
            model_name='messagereminder',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
