# Generated by Django 4.2.23 on 2026-05-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_add_message_reminder'),
    ]

    operations = []
