# Generated by Django 4.2.23 on 2026-05-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_rename_chat_messag_is_sent_idx_chat_messag_is_sent_872aa0_idx_and_more'),
    ]

    operations = []
