# Generated by Django 4.2.23 on 2026-05-23 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0010_message_is_revoked_message_revoked_at_and_more'),
    ]

    operations = []
