# Generated by Django 4.2.23 on 2026-05-27 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0011_message_hidden_by_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='rich_body',
            field=models.JSONField(blank=True, help_text='Tiptap JSON document for rich rendering. content holds the searchable plain-text copy.', null=True),
        ),
        migrations.CreateModel(
            name='MessageMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('mentioned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_mentions', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='chat.message')),
            ],
            options={
                'indexes': [models.Index(fields=['mentioned_user', 'created_at'], name='chat_mention_user_idx')],
                'unique_together': {('message', 'mentioned_user')},
            },
        ),
    ]
