# Generated by Django 4.2.23 on 2026-07-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='client_message_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Client idempotency key for retried sends; NULL for legacy messages.',
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(
                fields=('sender', 'client_message_id'),
                name='chat_message_sender_client_msg_uniq',
            ),
        ),
    ]
