# Generated by Django 4.2.23 on 2026-05-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_add_rich_body_and_message_mention'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='transcript',
            field=models.TextField(blank=True, default=None, help_text='AI-generated transcript for audio attachments', null=True),
        ),
    ]
