# Generated by Django 4.2.23 on 2026-05-28 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0013_add_attachment_transcript'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('last_read_at', models.DateTimeField(help_text='Timestamp of the latest thread reply seen by this user.')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='parent_message',
            field=models.ForeignKey(blank=True, help_text='Root message this is a thread reply to. Null = root/main-timeline message.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_replies', to='chat.message'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['parent_message', 'created_at'], name='chat_messag_parent__013672_idx'),
        ),
        migrations.AddField(
            model_name='threadreadstatus',
            name='root_message',
            field=models.ForeignKey(help_text='The parent (root) message whose thread was read.', on_delete=django.db.models.deletion.CASCADE, related_name='thread_read_statuses', to='chat.message'),
        ),
        migrations.AddField(
            model_name='threadreadstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_read_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='threadreadstatus',
            index=models.Index(fields=['user', 'root_message'], name='chat_thread_user_id_d7ca1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='threadreadstatus',
            unique_together={('user', 'root_message')},
        ),
    ]
