# Generated by Django 4.2.23 on 2026-05-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_message_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Longer description shown in the channel details drawer'),
        ),
        migrations.AddField(
            model_name='chat',
            name='topic',
            field=models.CharField(blank=True, default='', help_text='Short topic line shown in the channel header', max_length=500),
        ),
    ]
