# Generated by Django 4.2.23 on 2026-05-30 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0016_add_chat_topic_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(help_text='Chat channel this pin belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pinned_messages', to='chat.chat')),
                ('message', models.ForeignKey(help_text='Message that was pinned', on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='chat.message')),
                ('pinned_by', models.ForeignKey(help_text='User who pinned the message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chat', '-created_at'], name='chat_pinned_chat_id_9ca9c4_idx')],
                'unique_together': {('chat', 'message')},
            },
        ),
    ]
