# Generated by Django 4.2.23 on 2026-05-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_add_pinned_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatparticipant',
            name='is_muted',
            field=models.BooleanField(default=False, help_text='When True, suppress notifications for this chat for this user'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='notification_level',
            field=models.CharField(choices=[('all', 'All messages'), ('mentions', 'Mentions only'), ('none', 'Nothing')], default='all', help_text='Notification level for this chat', max_length=20),
        ),
    ]
