# Generated by Django 4.2.23 on 2026-05-30 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0019_add_saved_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True, default='', help_text='Plain-text content (mirrors rich_body for search/display)')),
                ('rich_body', models.JSONField(blank=True, help_text='Tiptap JSON document (same format as Message.rich_body)', null=True)),
                ('attachment_ids', models.JSONField(blank=True, default=list, help_text='List of MessageAttachment IDs to link when the message is created')),
                ('mention_ids', models.JSONField(blank=True, default=list, help_text='List of user IDs to @-mention')),
                ('scheduled_at', models.DateTimeField(db_index=True, help_text='When the message should be sent (UTC)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, default='', help_text='Celery task ID — used to revoke the task on cancellation', max_length=255)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error detail if status=failed')),
                ('chat', models.ForeignKey(help_text='Chat the message will be sent to', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='chat.chat')),
                ('reply_to', models.ForeignKey(blank=True, help_text='Message being quote-replied to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_replies', to='chat.message')),
                ('sender', models.ForeignKey(help_text='User who scheduled the message', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to=settings.AUTH_USER_MODEL)),
                ('sent_message', models.ForeignKey(blank=True, help_text='The Message created when this scheduled send fired', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_scheduled', to='chat.message')),
            ],
            options={
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['sender', 'status', 'scheduled_at'], name='chat_schedu_sender__73be39_idx'), models.Index(fields=['chat', 'status', 'scheduled_at'], name='chat_schedu_chat_id_63099e_idx')],
            },
        ),
    ]
