# Generated by Django 4.2.23 on 2026-06-20 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0002_customerstatuslabel_customer_status_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInternalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.JSONField()),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_format', models.CharField(default='rich_text_json', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_internal_notes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='customer.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInternalNoteAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('note.created', 'Note Created'), ('note.edited', 'Note Edited'), ('note.deleted', 'Note Deleted')], db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note_id', models.IntegerField(blank=True, null=True)),
                ('note_body', models.TextField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_note_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_note_audit_log', to='customer.customer')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['customer', '-timestamp'], name='audit_note_ts_idx'), models.Index(fields=['customer', 'event_type', '-timestamp'], name='audit_note_type_ts_idx')],
            },
        ),
    ]
