# Generated by Django 4.2.23 on 2026-05-20 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_user_profile_fields'),
        ('customer', '0004_region_customer_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domains', models.JSONField(default=list)),
                ('industry', models.CharField(blank=True, default='', max_length=200)),
                ('plan', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_organisations', to='core.project')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisations', to='customer.region')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customer.customerorganisation'),
        ),
        migrations.AddConstraint(
            model_name='customerorganisation',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='customerorganisation_unique_name_per_project'),
        ),
    ]
