# Generated by Django 4.2.23 on 2026-05-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customerorganisation_customer_organisation_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customerorganisation',
            name='customerorganisation_unique_name_per_project',
        ),
        migrations.RemoveField(
            model_name='customerorganisation',
            name='project',
        ),
        migrations.AddConstraint(
            model_name='customerorganisation',
            constraint=models.UniqueConstraint(fields=('name',), name='customerorganisation_unique_name'),
        ),
    ]
