# Generated by Django 4.2.23 on 2026-05-26 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_organization_nullable'),
        ('customer', '0006_remove_customerorganisation_customerorganisation_unique_name_per_project_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customerorganisation',
            name='customerorganisation_unique_name',
        ),
        migrations.AddField(
            model_name='customerorganisation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_organisations', to='core.organization'),
        ),
        migrations.AddConstraint(
            model_name='customerorganisation',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='customerorganisation_unique_name_per_org'),
        ),
    ]
