# Generated by Django 4.2.23 on 2026-05-27 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customerorganisation_add_organization'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='region',
            name='region_unique_name_per_project',
        ),
        migrations.AddField(
            model_name='region',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='customer.customerorganisation'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='region_unique_name_per_org'),
        ),
    ]
