# Generated by Django 4.2.23 on 2026-05-27 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_organization_nullable'),
        ('customer', '0008_region_add_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='core.project'),
        ),
    ]
