# Generated by Django 4.2.23 on 2026-06-21 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customerinternalnote_customerinternalnoteauditlog'),
        ('customer', '0010_add_user_to_customer'),
    ]

    operations = [
    ]
