# Generated by Django 4.2.23 on 2026-06-03 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meetings.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
        ('core', '0001_initial'),
        ('decision', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('order_index', models.PositiveIntegerField()),
                ('is_priority', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(max_length=50)),
                ('artifact_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('objective', models.TextField()),
                ('summary', models.TextField(blank=True, default='', help_text='Concise outcomes / takeaways for scanning and search snippets.')),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('layout_config', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Archived meetings are treated as immutable knowledge records.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft-delete flag (added in migration 0002).')),
                ('minutes_published', models.BooleanField(default=False, help_text='Whether the meeting minutes have been published to all participants.')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('meeting.status_changed', 'Status Changed'), ('meeting.title_changed', 'Title Changed'), ('meeting.objective_changed', 'Objective Changed'), ('meeting.summary_changed', 'Summary Changed'), ('meeting.type_changed', 'Type Changed'), ('meeting.datetime_changed', 'Date/Time Changed'), ('meeting.participant_added', 'Participant Added'), ('meeting.participant_removed', 'Participant Removed'), ('meeting.agenda_item_added', 'Agenda Item Added'), ('meeting.agenda_item_edited', 'Agenda Item Edited'), ('meeting.agenda_item_deleted', 'Agenda Item Deleted'), ('meeting.document_edited', 'Document Edited'), ('meeting.action_item_added', 'Action Item Added'), ('meeting.action_item_edited', 'Action Item Edited'), ('meeting.action_item_resolved', 'Action Item Resolved'), ('meeting.decision_created', 'Decision Created'), ('meeting.decision_updated', 'Decision Updated'), ('meeting.decision_deleted', 'Decision Deleted'), ('meeting.task_created', 'Task Created'), ('meeting.task_updated', 'Task Updated'), ('meeting.task_deleted', 'Task Deleted'), ('meeting.template_applied', 'Template Applied'), ('meeting.tags_changed', 'Tags Changed')], db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'Meeting Audit Log',
                'verbose_name_plural': 'Meeting Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MeetingDecisionOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_timestamp', models.DateTimeField()),
                ('creation_context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('yjs_state', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingTagDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('is_accepted', models.BooleanField(default=False, help_text='True once the invitee explicitly accepts; False while the invite is pending.')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_links', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingTypeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=160)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_type_definitions', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingTemplate',
            fields=[
                ('id', models.CharField(default=meetings.models._meeting_template_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('layout_config', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingTaskOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_origins', to='meetings.meeting')),
            ],
        ),
        migrations.AddField(
            model_name='meetingtaskorigin',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_origin', to='task.task'),
        ),
        migrations.AddField(
            model_name='meetingtagdefinition',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_tag_definitions', to='core.project'),
        ),
        migrations.AddField(
            model_name='meetingtagassignment',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='meetingtagassignment',
            name='tag_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='meetings.meetingtagdefinition'),
        ),
        migrations.AddField(
            model_name='meetingdocument',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_meeting_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingdocument',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='meetingdecisionorigin',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_decision_origins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingdecisionorigin',
            name='decision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_origin', to='decision.decision'),
        ),
        migrations.AddField(
            model_name='meetingdecisionorigin',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_origins', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='meetingauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_audit_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingauditlog',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_log', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='meetingactionitem',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.project'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='type_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='meetings.meetingtypedefinition'),
        ),
        migrations.AddField(
            model_name='artifactlink',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_links', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='meetings.meeting'),
        ),
        migrations.AddIndex(
            model_name='participantlink',
            index=models.Index(fields=['user', 'meeting'], name='mtgs_prt_usr_mtg'),
        ),
        migrations.AlterUniqueTogether(
            name='participantlink',
            unique_together={('meeting', 'user')},
        ),
        migrations.AddIndex(
            model_name='meetingtypedefinition',
            index=models.Index(fields=['project', 'slug'], name='mtgs_typedef_prj_slug'),
        ),
        migrations.AddConstraint(
            model_name='meetingtypedefinition',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='meetings_type_def_unique_project_slug'),
        ),
        migrations.AddIndex(
            model_name='meetingtaskorigin',
            index=models.Index(fields=['meeting', 'task'], name='mtgs_tkor_mtg_tsk'),
        ),
        migrations.AddConstraint(
            model_name='meetingtaskorigin',
            constraint=models.UniqueConstraint(fields=('meeting', 'task'), name='mtgs_tkor_unique_meeting_task'),
        ),
        migrations.AddIndex(
            model_name='meetingtagdefinition',
            index=models.Index(fields=['project', 'slug'], name='mtgs_tagdef_prj_slug'),
        ),
        migrations.AddConstraint(
            model_name='meetingtagdefinition',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='meetings_tag_def_unique_project_slug'),
        ),
        migrations.AddIndex(
            model_name='meetingtagassignment',
            index=models.Index(fields=['tag_definition', 'meeting'], name='mtgs_tagas_tag_mtg'),
        ),
        migrations.AddConstraint(
            model_name='meetingtagassignment',
            constraint=models.UniqueConstraint(fields=('meeting', 'tag_definition'), name='meetings_tag_assign_unique_meeting_tag'),
        ),
        migrations.AddIndex(
            model_name='meetingdecisionorigin',
            index=models.Index(fields=['meeting', 'decision'], name='mtgs_dcor_mtg_dec'),
        ),
        migrations.AddIndex(
            model_name='meetingdecisionorigin',
            index=models.Index(fields=['meeting', 'origin_timestamp'], name='mtgs_dcor_mtg_time'),
        ),
        migrations.AddConstraint(
            model_name='meetingdecisionorigin',
            constraint=models.UniqueConstraint(fields=('meeting', 'decision'), name='mtgs_dcor_unique_meeting_decision'),
        ),
        migrations.AddIndex(
            model_name='meetingauditlog',
            index=models.Index(fields=['meeting', '-timestamp'], name='audit_mtg_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingauditlog',
            index=models.Index(fields=['meeting', 'event_type', '-timestamp'], name='audit_mtg_type_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingauditlog',
            index=models.Index(fields=['meeting', 'actor', '-timestamp'], name='audit_mtg_actor_ts_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingauditlog',
            constraint=models.CheckConstraint(check=models.Q(('id__isnull', False)), name='audit_log_has_id'),
        ),
        migrations.AddIndex(
            model_name='meetingactionitem',
            index=models.Index(fields=['meeting', 'order_index'], name='mtgs_actitem_meet_ord'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['project', '-created_at'], name='mtgs_mtg_prj_crtd_d'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['project', 'is_archived', '-updated_at'], name='mtgs_mtg_prj_arch_u'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['project', 'scheduled_date'], name='mtgs_mtg_prj_sched'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['project', 'type_definition'], name='mtgs_mtg_prj_type'),
        ),
        migrations.AddIndex(
            model_name='artifactlink',
            index=models.Index(fields=['artifact_type', 'artifact_id'], name='mtgs_artlink_type_artid'),
        ),
        migrations.AlterUniqueTogether(
            name='artifactlink',
            unique_together={('meeting', 'artifact_type', 'artifact_id')},
        ),
        migrations.AlterUniqueTogether(
            name='agendaitem',
            unique_together={('meeting', 'order_index')},
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION raise_audit_immutable_error()
            RETURNS TRIGGER AS $$
            BEGIN
                -- Allow SET NULL cascade when the referenced user is deleted:
                -- only actor_id changes (non-null -> null), everything else stays the same.
                IF (
                    OLD.actor_id IS NOT NULL AND
                    NEW.actor_id IS NULL AND
                    OLD.event_type = NEW.event_type AND
                    OLD.meeting_id = NEW.meeting_id AND
                    OLD.before IS NOT DISTINCT FROM NEW.before AND
                    OLD.after IS NOT DISTINCT FROM NEW.after AND
                    OLD.context IS NOT DISTINCT FROM NEW.context
                ) THEN
                    RETURN NEW;
                END IF;
                RAISE EXCEPTION 'Meeting audit log entries are immutable and cannot be modified';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER meeting_audit_log_immutable
            BEFORE UPDATE OR DELETE ON meetings_meetingauditlog
            FOR EACH ROW
            EXECUTE FUNCTION raise_audit_immutable_error();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS meeting_audit_log_immutable ON meetings_meetingauditlog;
            DROP FUNCTION IF EXISTS raise_audit_immutable_error();
            """,
        ),
    ]
