# Generated by Django 4.2.23 on 2026-04-01 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meetings.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0003_drop_meetingtemplate_block_config'),
    ]

    operations = []
