# Generated by Django 4.2.23 on 2026-04-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0003_meeting_origin_timestamps_and_constraints"),
    ]

    operations = []
