# Generated by Django 4.2.23 on 2026-04-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_merge_meetingdocument_yjs_and_template_user'),
    ]

    operations = []
