# Generated by Django 4.2.23 on 2026-04-06 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0006_meeting_lifecycle_states'),
    ]

    operations = []
