# Generated by Django 4.2.23 on 2026-05-26 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_meetingauditlog_meetingauditlog_audit_log_has_id'),
        ('meetings', '0013_participantlink_is_accepted'),
    ]

    operations = [
    ]
