# Generated by Django 4.2.23 on 2026-05-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0014_merge_20260526_0244'),
    ]

    operations = []
