# Generated by Django 4.2.23 on 2026-05-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0014_merge_20260526_0244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingauditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Meeting Audit Log', 'verbose_name_plural': 'Meeting Audit Logs'},
        ),
        migrations.AlterField(
            model_name='meetingauditlog',
            name='context',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='meetingauditlog',
            name='event_type',
            field=models.CharField(choices=[('meeting.status_changed', 'Status Changed'), ('meeting.title_changed', 'Title Changed'), ('meeting.objective_changed', 'Objective Changed'), ('meeting.summary_changed', 'Summary Changed'), ('meeting.type_changed', 'Type Changed'), ('meeting.datetime_changed', 'Date/Time Changed'), ('meeting.participant_added', 'Participant Added'), ('meeting.participant_removed', 'Participant Removed'), ('meeting.agenda_item_added', 'Agenda Item Added'), ('meeting.agenda_item_edited', 'Agenda Item Edited'), ('meeting.agenda_item_deleted', 'Agenda Item Deleted'), ('meeting.document_edited', 'Document Edited'), ('meeting.action_item_added', 'Action Item Added'), ('meeting.action_item_edited', 'Action Item Edited'), ('meeting.action_item_resolved', 'Action Item Resolved'), ('meeting.decision_created', 'Decision Created'), ('meeting.decision_updated', 'Decision Updated'), ('meeting.decision_deleted', 'Decision Deleted'), ('meeting.task_created', 'Task Created'), ('meeting.task_updated', 'Task Updated'), ('meeting.task_deleted', 'Task Deleted'), ('meeting.template_applied', 'Template Applied'), ('meeting.tags_changed', 'Tags Changed')], db_index=True, max_length=64),
        ),
    ]
