# Generated by Django 4.2.23 on 2026-06-07 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0018_fix_audit_trigger_allow_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingauditlog',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='meetings.meeting'),
        ),
        migrations.AlterField(
            model_name='meetingdecisionorigin',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_origins', to='meetings.meeting'),
        ),
    ]
