# Generated by Django 4.2.23 on 2026-06-03 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meta_ads', '0001_initial'),
        ('core', '__first__'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCopyVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('source_mode', models.CharField(choices=[('existing', 'Existing creative'), ('custom', 'Custom content'), ('external_url', 'External URL')], max_length=32)),
                ('source_ref', models.TextField(blank=True, default='')),
                ('hook', models.TextField(blank=True, default='')),
                ('headline', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('cta', models.CharField(blank=True, default='', max_length=64)),
                ('instruction', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(default='gemini-2.5-flash-lite', max_length=64)),
                ('prompt_version', models.CharField(default='v1', max_length=32)),
                ('batch_id', models.UUIDField(blank=True, db_index=True, help_text='Groups variations generated from the same batch call.', null=True)),
                ('batch_position', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed')], db_index=True, default='draft', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adcopyvariation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adcopyvariation',
            name='creative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copy_variations', to='meta_ads.metaadcreative'),
        ),
        migrations.AddField(
            model_name='adcopyvariation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_copy_variations', to='core.project'),
        ),
        migrations.AddIndex(
            model_name='adcopyvariation',
            index=models.Index(fields=['project', 'status', '-created_at'], name='ad_copy_var_project_5f6c42_idx'),
        ),
        migrations.AddIndex(
            model_name='adcopyvariation',
            index=models.Index(fields=['project', 'batch_id', 'status'], name='ad_copy_var_project_ef5425_idx'),
        ),
        migrations.AddIndex(
            model_name='adcopyvariation',
            index=models.Index(fields=['creative', 'status', '-created_at'], name='ad_copy_var_creativ_ae4311_idx'),
        ),
    ]
