# Generated by Django 4.2.23 on 2026-05-04 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meta_ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCopyVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('source_mode', models.CharField(choices=[('existing', 'Existing creative'), ('custom', 'Custom content'), ('external_url', 'External URL')], max_length=32)),
                ('source_ref', models.TextField(blank=True, default='')),
                ('hook', models.TextField(blank=True, default='')),
                ('headline', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('cta', models.CharField(blank=True, default='', max_length=64)),
                ('instruction', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(default='gemini-2.5-flash-lite', max_length=64)),
                ('prompt_version', models.CharField(default='v1', max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copy_variations', to='meta_ads.metaadcreative')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
