# Generated by Django 4.2.23 on 2026-05-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_copy_variation', '0001_initial'),
    ]

    operations = []
