# Generated by Codex on 2026-05-20

from django.db import migrations, models
import django.db.models.deletion


def backfill_project_and_status(apps, schema_editor):
    AdCopyVariation = apps.get_model('ad_copy_variation', 'AdCopyVariation')

    rows = (
        AdCopyVariation.objects
        .select_related('creative__ad_account')
        .all()
    )
    for row in rows.iterator():
        update_fields = ['status']
        row.status = 'reviewed'
        ad_account = getattr(getattr(row, 'creative', None), 'ad_account', None)
        project_id = getattr(ad_account, 'project_id', None)
        if project_id:
            row.project_id = project_id
            update_fields.append('project')
        row.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_user_profile_fields'),
        ('ad_copy_variation', '0002_adcopyvariation_batch_id'),
    ]

    operations = []
