# Generated by Django 4.2.23 on 2026-05-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_nullable_legacy_heartbeat_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingevent',
            name='event_type',
            field=models.CharField(choices=[('TASK_OPEN', 'Task Open'), ('FIRST_INTERACTION', 'First Interaction'), ('TASK_WRITE', 'Task Write'), ('IDLE_START', 'Idle Start'), ('IDLE_END', 'Idle End')], max_length=30),
        ),
    ]
