# Generated by Django 4.2.23 on 2026-05-26 13:53

from django.db import migrations, models


def backfill_source_and_schema_version(apps, schema_editor):
    TrackingEvent = apps.get_model('tracking', 'TrackingEvent')
    TrackingEvent.objects.filter(source__isnull=True).update(source='middleware')
    TrackingEvent.objects.filter(schema_version__isnull=True).update(schema_version=1)


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_trackingevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingevent',
            name='schema_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='source',
            field=models.CharField(choices=[('middleware', 'Middleware'), ('explicit', 'Explicit'), ('client', 'Client')], db_index=True, default='middleware', max_length=20),
        ),
        migrations.RunPython(
            backfill_source_and_schema_version,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
