# Generated by Django 4.2.23 on 2026-05-25 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customerorganisation_customer_organisation_and_more'),
        ('csm', '0002_queue_organisation_ticket_customeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_users', to='customer.customerorganisation'),
        ),
    ]
