# Generated by Django 4.2.23 on 2026-05-27 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_organization_nullable'),
        ('customer', '0009_region_project_nullable'),
        ('csm', '0003_customeruser_organisation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='queue',
            unique_together={('organisation', 'name')},
        ),
        migrations.AlterField(
            model_name='queue',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='core.project'),
        ),
    ]
