# Generated by Django 4.2.23 on 2026-06-08 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_add_user_to_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csm', '0006_conversation_and_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickReplyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(help_text='Short label shown in the template picker', max_length=200)),
                ('content', models.TextField(help_text='Plain-text content inserted into the composer')),
                ('rich_body', models.JSONField(blank=True, help_text='Optional Tiptap JSON', null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tag strings for filtering')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_reply_templates', to='customer.customerorganisation')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
