# Generated by Django 4.2.23 on 2026-06-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0009_merge_parallel_chains'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='conversation_images/'),
        ),
    ]
