# Generated by Django 4.2.23 on 2026-06-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0009_queue_ticketform_slug'),
        ('csm', '0010_add_image_to_conversationmessage'),
    ]

    operations = [
    ]
