# Generated by Django 4.2.23 on 2026-06-19 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_backfill_org_admin_fallback'),
        ('csm', '0010_add_image_to_conversationmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(default='Default SLA Policy', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla_policy', to='core.project')),
            ],
            options={
                'verbose_name': 'SLA Policy',
                'verbose_name_plural': 'SLA Policies',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_response_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.CreateModel(
            name='SLAPriorityTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('first_response_minutes', models.PositiveIntegerField(default=480, help_text='Minutes until first response is due (e.g. 60 = 1 hour)')),
                ('resolution_minutes', models.PositiveIntegerField(default=1440, help_text='Minutes until resolution is due (e.g. 480 = 8 hours)')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_targets', to='csm.slapolicy')),
            ],
            options={
                'ordering': ['policy', 'priority'],
                'unique_together': {('policy', 'priority')},
            },
        ),
    ]
