# Generated by Django 4.2.23 on 2026-06-23 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0011_merge_20260620_0728'),
        ('csm', '0011_ticket_priority_sla_policy'),
    ]

    operations = [
    ]
