# Generated by Django 4.2.23 on 2026-07-04 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_project_slug_org_admin'),
        ('csm', '0015_merge_sla_and_support_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pending_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('pending_customer', 'Pending Customer Response'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='todo', max_length=50),
        ),
        migrations.CreateModel(
            name='TicketStatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('from_status', models.CharField(max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_status_transitions', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('slug', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#94a3b8', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_builtin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_statuses', to='core.project')),
            ],
            options={
                'verbose_name_plural': 'ticket statuses',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TicketAutoResolveConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
                ('days_until_resolve', models.PositiveIntegerField(default=3)),
                ('notification_message', models.TextField(default='This ticket has been automatically resolved as we did not hear back from you. Please reply if you still need help and we will reopen it.')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_auto_resolve_config', to='core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='ticketstatustransition',
            constraint=models.UniqueConstraint(fields=('project', 'from_status', 'to_status'), name='csm_ticketstatustransition_unique'),
        ),
        migrations.AddConstraint(
            model_name='ticketstatus',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='csm_ticketstatus_unique_slug_per_project'),
        ),
    ]
