# Generated by Django 4.2.23 on 2026-07-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0017_recolor_builtin_ticket_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketautoresolveconfig',
            name='days_until_resolve',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
