# Generated by Django 4.2.23 on 2026-07-09 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0016_quickreplytemplate_slug_and_templatetag'),
        ('csm', '0018_alter_ticketautoresolveconfig_days_until_resolve'),
    ]

    operations = [
    ]
