# Generated by Django 4.2.23 on 2026-07-11 07:05

import csm.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_organization_activity_event'),
        ('csm', '0019_merge_20260709_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHoursCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('schedule', models.JSONField(default=csm.models.default_operating_hours)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours_calendars', to='core.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_policies', to='csm.businesshourscalendar'),
        ),
    ]
