# Generated by Django 4.2.23 on 2026-07-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0020_businesshourscalendar_slapolicy_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='slapolicy',
            name='pause_on_pending',
            field=models.BooleanField(default=True),
        ),
    ]
