# Generated by Django 4.2.23 on 2026-07-12 10:26

from django.db import migrations, models
import django.db.models.deletion


def mark_existing_policies_default(apps, schema_editor):
    # Until now each project held a single policy; it is that project's fallback.
    SLAPolicy = apps.get_model('csm', 'SLAPolicy')
    SLAPolicy.objects.update(is_default=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_organization_activity_event'),
        ('csm', '0021_slapolicy_pause_on_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='sla_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queues', to='csm.slapolicy'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Fallback policy for queues in this project with no policy assigned.'),
        ),
        migrations.AlterField(
            model_name='slapolicy',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='core.project'),
        ),
        migrations.RunPython(mark_existing_policies_default, migrations.RunPython.noop),
    ]
