# Generated by Django 4.2.23 on 2026-07-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0022_queue_sla_policy_slapolicy_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='first_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
