# Generated by Django 4.2.23 on 2026-07-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0023_ticket_first_responded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='first_response_breach_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_breach_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='csmnotification',
            name='notification_type',
            field=models.CharField(choices=[('org_invitation', 'Organisation Invitation'), ('sla_breach', 'SLA Breach')], max_length=30),
        ),
    ]
