# Generated by Django 4.2.23 on 2026-07-16 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0020_merge_20260712_0945'),
        ('csm', '0024_ticket_first_response_breach_notified_and_more'),
    ]

    operations = [
    ]
