# Generated by Django 4.2.23 on 2026-07-16 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0025_merge_20260716_0543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slapolicy',
            options={'ordering': ['id'], 'verbose_name': 'SLA Policy', 'verbose_name_plural': 'SLA Policies'},
        ),
    ]
