# Generated by Django 4.2.23 on 2026-06-09 14:39

from django.db import migrations, models

from core.slug_backfill import backfill_slugs


def backfill(apps, schema_editor):
    # mailchimp.Campaign has no usable text field; uuid-based slugs are generated.
    backfill_slugs(apps.get_model('mailchimp', 'Campaign'))


class Migration(migrations.Migration):

    dependencies = [
        ('mailchimp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
