"""Shared constants for Quick Start."""

BLUEPRINT_VERSION = 1

MODULE_TASKS = 'tasks'
MODULE_SPREADSHEET = 'spreadsheet'
MODULE_CALENDAR = 'calendar'
MODULE_DECISIONS = 'decisions'
MODULE_MIRO = 'miro'

MVP_MODULES = (
    MODULE_TASKS,
    MODULE_SPREADSHEET,
    MODULE_CALENDAR,
)

ALL_MODULES = MVP_MODULES + (MODULE_DECISIONS, MODULE_MIRO)

DEFAULT_SELECTED_MODULES = {
    MODULE_TASKS: True,
    MODULE_SPREADSHEET: True,
    MODULE_CALENDAR: True,
    MODULE_DECISIONS: True,
    MODULE_MIRO: True,
}

MIN_PROMPT_LENGTH = 10
MAX_PROMPT_LENGTH = 3000
MAX_SUPPLEMENT_LENGTH = 2000
MAX_COMBINED_INPUT_LENGTH = 5000
MIN_TASKS_WHEN_ENABLED = 5
MIN_CALENDAR_EVENTS_WHEN_ENABLED = 1
MIN_DECISIONS_WHEN_ENABLED = 2
MIN_MIRO_BOARDS_WHEN_ENABLED = 1
MIN_MIRO_STICKY_NOTES_PER_BOARD = 2
