# Generated by Django 4.2.23 on 2026-04-01 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('task', '0005_alter_approvalrecord_options_and_more'),
        ('decision', '0004_merge_predraft_migrations'),
        ('calendars', '0002_initial'),
    ]

    operations = []
