# Generated by Django 4.2.23 on 2026-05-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_calendarevent'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.UniqueConstraint(condition=models.Q(('task__isnull', False)), fields=('event_type', 'task'), name='unique_cal_event_per_task_type'),
        ),
    ]
