# Generated by Django 4.2.23 on 2026-06-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='topic',
            field=models.CharField(blank=True, default='other', max_length=64),
        ),
    ]
