# Generated by Django 4.2.23 on 2026-04-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0005_decision_planned_decision_date'),
    ]

    operations = []
