# Generated by Django 4.2.23 on 2026-06-09 14:45

from django.db import migrations, models

from core.slug_backfill import backfill_slugs


def backfill(apps, schema_editor):
    backfill_slugs(apps.get_model('decision', 'Decision'), source_field='title')


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0006_alter_decisionstatetransition_from_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='decision',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
