# Generated by Django 4.2.23 on 2026-06-03 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


SYSTEM_CATEGORIES = [
    ('identifier', 'Identifier', 'Columns that identify an entity: name, ID, campaign, ad set'),
    ('financial', 'Financial', 'Monetary values: spend, cost, budget, revenue, ROAS, CPM, CPC'),
    ('engagement', 'Engagement', 'User interaction counts: impressions, clicks, reach, video views'),
    ('conversion', 'Conversion', 'Goal-completion events: purchases, leads, add-to-cart, sign-ups'),
    ('performance_ratio', 'Performance Ratio', 'Derived rate metrics: CTR, CVR, CPA, frequency'),
    ('temporal', 'Temporal', 'Date and time columns: date, week, month, reporting period'),
    ('unknown', 'Unknown', 'Could not be automatically categorised — user can reassign'),
]

META_ADS_COLUMNS = [
    {'canonical_name': 'campaign_name', 'aliases': ['campaign name', 'campaign', 'campaign_name'], 'category': 'identifier', 'value_type': 'string', 'description': 'Campaign name'},
    {'canonical_name': 'ad_set_name', 'aliases': ['ad set name', 'adset name', 'adset_name', 'ad_set_name'], 'category': 'identifier', 'value_type': 'string', 'description': 'Ad set name'},
    {'canonical_name': 'ad_name', 'aliases': ['ad name', 'ad_name', 'creative name', 'creative_name'], 'category': 'identifier', 'value_type': 'string', 'description': 'Ad name / creative'},
    {'canonical_name': 'campaign_id', 'aliases': ['campaign id', 'campaign_id'], 'category': 'identifier', 'value_type': 'string', 'description': 'Campaign ID'},
    {'canonical_name': 'ad_set_id', 'aliases': ['ad set id', 'adset id', 'adset_id', 'ad_set_id'], 'category': 'identifier', 'value_type': 'string', 'description': 'Ad set ID'},
    {'canonical_name': 'ad_id', 'aliases': ['ad id', 'ad_id'], 'category': 'identifier', 'value_type': 'string', 'description': 'Ad ID'},
    {'canonical_name': 'amount_spent', 'aliases': ['amount spent', 'amount_spent', 'spend', 'ad spend', 'ad_spend', 'cost', 'total spend', 'total_spend'], 'category': 'financial', 'value_type': 'number', 'description': 'Total amount spent (currency)'},
    {'canonical_name': 'cpm', 'aliases': ['cpm', 'cost per 1000 impressions', 'cost per thousand impressions'], 'category': 'financial', 'value_type': 'number', 'description': 'Cost per 1,000 impressions'},
    {'canonical_name': 'cpc', 'aliases': ['cpc', 'cost per click', 'cost per link click'], 'category': 'financial', 'value_type': 'number', 'description': 'Cost per click'},
    {'canonical_name': 'cpp', 'aliases': ['cpp', 'cost per purchase', 'cost per result'], 'category': 'financial', 'value_type': 'number', 'description': 'Cost per purchase / result'},
    {'canonical_name': 'impressions', 'aliases': ['impressions', 'impression'], 'category': 'engagement', 'value_type': 'number', 'description': 'Total impressions'},
    {'canonical_name': 'reach', 'aliases': ['reach', 'unique reach'], 'category': 'engagement', 'value_type': 'number', 'description': 'Unique accounts reached'},
    {'canonical_name': 'clicks', 'aliases': ['clicks', 'all clicks', 'total clicks'], 'category': 'engagement', 'value_type': 'number', 'description': 'Total clicks (all)'},
    {'canonical_name': 'link_clicks', 'aliases': ['link clicks', 'link_clicks', 'unique link clicks'], 'category': 'engagement', 'value_type': 'number', 'description': 'Link clicks'},
    {'canonical_name': 'frequency', 'aliases': ['frequency'], 'category': 'engagement', 'value_type': 'number', 'description': 'Average times each person saw the ad'},
    {'canonical_name': 'video_views', 'aliases': ['video views', 'video_views', '3-second video views', 'thruplays', 'thruplay', '2-second continuous video views'], 'category': 'engagement', 'value_type': 'number', 'description': 'Video views'},
    {'canonical_name': 'purchases', 'aliases': ['purchases', 'purchase', 'conversions', 'results', 'website purchases', 'omni purchases'], 'category': 'conversion', 'value_type': 'number', 'description': 'Purchase / conversion events'},
    {'canonical_name': 'purchase_roas', 'aliases': ['purchase roas', 'purchase_roas', 'roas', 'website purchase roas'], 'category': 'conversion', 'value_type': 'number', 'description': 'Return on ad spend (purchases)'},
    {'canonical_name': 'add_to_cart', 'aliases': ['add to cart', 'add_to_cart', 'adds to cart', 'website adds to cart'], 'category': 'conversion', 'value_type': 'number', 'description': 'Add-to-cart events'},
    {'canonical_name': 'leads', 'aliases': ['leads', 'lead', 'on-facebook leads', 'website leads'], 'category': 'conversion', 'value_type': 'number', 'description': 'Lead generation events'},
    {'canonical_name': 'ctr', 'aliases': ['ctr', 'click-through rate', 'click through rate', 'ctr (all)', 'all ctr'], 'category': 'performance_ratio', 'value_type': 'number', 'description': 'Click-through rate (all clicks / impressions)'},
    {'canonical_name': 'link_ctr', 'aliases': ['link ctr', 'link_ctr', 'ctr (link click-through rate)'], 'category': 'performance_ratio', 'value_type': 'number', 'description': 'Link click-through rate'},
]


def seed_system_agent_state(apps, schema_editor):
    WorkflowDef = apps.get_model('agent', 'AgentWorkflowDefinition')
    WorkflowStep = apps.get_model('agent', 'AgentWorkflowStep')
    FieldCategory = apps.get_model('agent', 'FieldCategory')
    DataSchemaTemplate = apps.get_model('agent', 'DataSchemaTemplate')

    workflow, _ = WorkflowDef.objects.update_or_create(
        is_system=True,
        name='Default Analysis Workflow',
        defaults={
            'description': 'Analyze uploaded data with column mapping, criteria generation, confirmation, decision, and tasks',
            'is_default': True,
            'status': 'active',
            'is_deleted': False,
        },
    )
    WorkflowStep.objects.filter(workflow=workflow).delete()
    workflow_steps = [
        ('Detect Columns', 'detect_columns', 1, {}, 'Identify each column in the uploaded file before running analysis.'),
        ('Confirm Column Mapping', 'await_confirmation', 2, {'message': 'Please review the detected column mapping. Correct any misidentified columns, then confirm to continue.'}, 'Pause so the user can review and correct the auto-detected column names.'),
        ('Normalize Data', 'normalize_data', 3, {}, 'Rename spreadsheet columns to the confirmed standard names.'),
        ('Generate Criteria', 'generate_criteria', 4, {}, 'Use the column names to generate success criteria that guide the downstream analysis workflow.'),
        ('Analyze Data', 'analyze_data', 5, {}, ''),
        ('Confirm Analysis', 'await_confirmation', 6, {'message': 'Analysis complete. Would you like to create a decision based on these findings?'}, ''),
        ('Create Decision', 'create_decision', 7, {}, ''),
        ('Confirm Decision', 'await_confirmation', 8, {'message': 'Decision draft created. Would you like to create tasks based on the recommendations?'}, ''),
        ('Create Tasks', 'create_tasks', 9, {}, ''),
    ]
    WorkflowStep.objects.bulk_create([
        WorkflowStep(
            workflow=workflow,
            name=name,
            step_type=step_type,
            order=order,
            config=config,
            description=description,
        )
        for name, step_type, order, config, description in workflow_steps
    ])

    for name, display_name, description in SYSTEM_CATEGORIES:
        FieldCategory.objects.update_or_create(
            name=name,
            defaults={
                'display_name': display_name,
                'description': description,
                'is_system': True,
                'project': None,
                'is_deleted': False,
            },
        )

    DataSchemaTemplate.objects.update_or_create(
        name='Meta Ads Performance',
        project=None,
        defaults={
            'source_platform': 'meta_ads',
            'description': 'Meta Ads Manager export — campaigns, ad sets, and ads performance data',
            'is_system': True,
            'is_learned': False,
            'match_threshold': 0.5,
            'usage_count': 0,
            'column_definitions': META_ADS_COLUMNS,
            'is_deleted': False,
        },
    )


def unseed_system_agent_state(apps, schema_editor):
    WorkflowDef = apps.get_model('agent', 'AgentWorkflowDefinition')
    FieldCategory = apps.get_model('agent', 'FieldCategory')
    DataSchemaTemplate = apps.get_model('agent', 'DataSchemaTemplate')

    WorkflowDef.objects.filter(is_system=True, name='Default Analysis Workflow').delete()
    DataSchemaTemplate.objects.filter(is_system=True, name='Meta Ads Performance', project=None).delete()
    FieldCategory.objects.filter(is_system=True, project=None).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('miro', '0001_initial'),
        ('core', '__first__'),
        ('spreadsheet', '0001_initial'),
        ('decision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('analysis', 'Analysis'), ('decision_draft', 'Decision Draft'), ('task_created', 'Task Created'), ('confirmation_request', 'Confirmation Request'), ('approval_request', 'Approval Request'), ('follow_up_prompt', 'Follow-up Prompt'), ('error', 'Error')], default='text', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentPendingExternalApproval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(help_text='Registry key, e.g. task, miro_board, calendar_event, forward_message.', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('draft', models.JSONField(default=dict)),
                ('commit_context', models.JSONField(default=dict)),
                ('destination_options', models.JSONField(default=list)),
                ('default_destination', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('approval_required', models.BooleanField(default=False, help_text='When true, external side effects require user approval before commit.')),
                ('is_pinned', models.BooleanField(default=False)),
                ('last_read_at', models.DateTimeField(blank=True, help_text='User read cursor; unread when assistant messages exist after this time.', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentStepExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_order', models.PositiveIntegerField()),
                ('step_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('awaiting', 'Awaiting Confirmation')], default='pending', max_length=20)),
                ('input_data', models.JSONField(blank=True, null=True)),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='AgentWorkflowDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentWorkflowRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('analyzing', 'Analyzing'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('awaiting_external_approval', 'Awaiting External Approval'), ('creating_decision', 'Creating Decision'), ('creating_tasks', 'Creating Tasks'), ('completed', 'Completed'), ('failed', 'Failed')], default='analyzing', max_length=40)),
                ('current_step_order', models.PositiveIntegerField(blank=True, null=True)),
                ('analysis_result', models.JSONField(blank=True, null=True)),
                ('created_tasks', models.JSONField(blank=True, default=list)),
                ('miro_snapshot', models.JSONField(blank=True, null=True)),
                ('success_criteria', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('chat_follow_up_started', models.BooleanField(default=False)),
                ('chat_followed_up', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentWorkflowStep',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('step_type', models.CharField(choices=[('analyze_data', 'Analyze Data'), ('call_dify', 'Call LLM (Legacy)'), ('call_llm', 'Call LLM'), ('create_decision', 'Create Decision'), ('create_tasks', 'Create Tasks'), ('generate_miro_snapshot', 'Generate Miro Snapshot'), ('create_miro_board', 'Create Miro Board'), ('custom_api', 'Custom API'), ('await_confirmation', 'Await Confirmation'), ('detect_columns', 'Detect Columns'), ('normalize_data', 'Normalize Data'), ('generate_criteria', 'Generate Criteria')], max_length=30)),
                ('order', models.PositiveIntegerField()),
                ('config', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DataSchemaTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable name, e.g. 'Meta Ads Performance'", max_length=255)),
                ('source_platform', models.CharField(choices=[('meta_ads', 'Meta Ads'), ('google_ads', 'Google Ads'), ('tiktok_ads', 'TikTok Ads'), ('klaviyo', 'Klaviyo'), ('mailchimp', 'Mailchimp'), ('custom', 'Custom / Unknown Platform')], default='custom', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('is_system', models.BooleanField(default=False, help_text='True for templates seeded from code; protected from automatic deletion')),
                ('is_learned', models.BooleanField(default=False, help_text='True when auto-generated from a high-confidence LLM detection result')),
                ('match_threshold', models.FloatField(default=0.5, help_text='Minimum fraction of file columns that must match for this template to be applied')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of uploaded files matched against this template — used for ranking')),
                ('column_definitions', models.JSONField(default=list, help_text='List of column spec objects (canonical_name, aliases, category, value_type, description)')),
            ],
            options={
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FieldCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text="Internal snake_case key, e.g. 'financial' or 'custom_brand_metric'", max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_system', models.BooleanField(default=False, help_text='True for built-in categories; these cannot be renamed or deleted')),
                ('color', models.CharField(blank=True, default='', help_text="Optional UI badge color, e.g. '#4CAF50'", max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Field categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportedCSVFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(help_text='Stored filename on disk', max_length=255)),
                ('original_filename', models.CharField(help_text='Original upload filename', max_length=255)),
                ('row_count', models.IntegerField(default=0)),
                ('column_count', models.IntegerField(default=0)),
                ('file_size', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedDataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField(help_text='0-based row index in the source file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict, help_text='Cell values keyed by canonical_name (or original header for unknown columns)')),
                ('quality_score', models.FloatField(default=1.0, help_text='Fraction of confirmed (non-unknown) fields with non-null values; 0.0-1.0')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_records', to='agent.importedcsvfile')),
            ],
            options={
                'ordering': ['row_index'],
            },
        ),
        migrations.CreateModel(
            name='ImportedDataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('original_name', models.CharField(help_text='Column header as it appears in the source file', max_length=255)),
                ('canonical_name', models.CharField(default='unknown', help_text="AI-detected snake_case name confirmed by the user, or 'unknown'", max_length=255)),
                ('value_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date')], default='string', max_length=20)),
                ('category', models.CharField(default='unknown', help_text='Semantic category key (references FieldCategory.name). Stored as a plain string so user-defined categories work without a FK constraint.', max_length=50)),
                ('confidence', models.FloatField(default=0.0, help_text='AI detection confidence 0.0-1.0')),
                ('position', models.IntegerField(default=0, help_text='0-based column index in the source file')),
                ('null_count', models.IntegerField(default=0)),
                ('unique_count', models.IntegerField(default=0)),
                ('min_value', models.TextField(blank=True, help_text='Minimum value as string (numeric columns)', null=True)),
                ('max_value', models.TextField(blank=True, help_text='Maximum value as string (numeric columns)', null=True)),
                ('sample_values', models.JSONField(default=list, help_text='Up to 5 representative non-null values, for UI display and LLM context')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_fields', to='agent.importedcsvfile')),
                ('matched_template', models.ForeignKey(blank=True, help_text='Schema template that identified this column, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_fields', to='agent.dataschematemplate')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='importedcsvfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_csv_files', to='core.project'),
        ),
        migrations.AddField(
            model_name='importedcsvfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_csv_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldcategory',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Null = global category; set = private to this project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_categories', to='core.project'),
        ),
        migrations.AddField(
            model_name='dataschematemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schema_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataschematemplate',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Null = global template; set = private to this project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schema_templates', to='core.project'),
        ),
        migrations.AddField(
            model_name='agentworkflowstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agent.agentworkflowdefinition'),
        ),
        migrations.AddField(
            model_name='agentworkflowrun',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_workflow_runs', to='decision.decision'),
        ),
        migrations.AddField(
            model_name='agentworkflowrun',
            name='miro_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_workflow_runs', to='miro.board'),
        ),
        migrations.AddField(
            model_name='agentworkflowrun',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to='agent.agentsession'),
        ),
        migrations.AddField(
            model_name='agentworkflowrun',
            name='spreadsheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_workflow_runs', to='spreadsheet.spreadsheet'),
        ),
        migrations.AddField(
            model_name='agentworkflowrun',
            name='workflow_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to='agent.agentworkflowdefinition'),
        ),
        migrations.AddField(
            model_name='agentworkflowdefinition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_definitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentworkflowdefinition',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_workflow_definitions', to='core.project'),
        ),
        migrations.AddField(
            model_name='agentstepexecution',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='agent.agentworkflowstep'),
        ),
        migrations.AddField(
            model_name='agentstepexecution',
            name='workflow_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='agent.agentworkflowrun'),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to='core.project'),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentpendingexternalapproval',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_external_approvals', to='agent.agentsession'),
        ),
        migrations.AddField(
            model_name='agentpendingexternalapproval',
            name='step_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_external_approvals', to='agent.agentstepexecution'),
        ),
        migrations.AddField(
            model_name='agentpendingexternalapproval',
            name='workflow_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_external_approvals', to='agent.agentworkflowrun'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent.agentsession'),
        ),
        migrations.AddIndex(
            model_name='importeddatarecord',
            index=models.Index(fields=['file', 'row_index'], name='agent_impor_file_id_9e1224_idx'),
        ),
        migrations.AddIndex(
            model_name='importeddatarecord',
            index=models.Index(fields=['file', 'quality_score'], name='agent_impor_file_id_6d3788_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='importeddatarecord',
            unique_together={('file', 'row_index')},
        ),
        migrations.AddIndex(
            model_name='importeddatafield',
            index=models.Index(fields=['file', 'category'], name='agent_impor_file_id_389ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='importeddatafield',
            index=models.Index(fields=['file', 'canonical_name'], name='agent_impor_file_id_448956_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='importeddatafield',
            unique_together={('file', 'position')},
        ),
        migrations.AddIndex(
            model_name='fieldcategory',
            index=models.Index(fields=['name', 'is_system'], name='agent_field_name_469f79_idx'),
        ),
        migrations.AddIndex(
            model_name='dataschematemplate',
            index=models.Index(fields=['source_platform', 'is_system'], name='agent_datas_source__33cb46_idx'),
        ),
        migrations.AddIndex(
            model_name='dataschematemplate',
            index=models.Index(fields=['project', 'is_system'], name='agent_datas_project_61ac9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentworkflowstep',
            unique_together={('workflow', 'order')},
        ),
        migrations.RunPython(seed_system_agent_state, unseed_system_agent_state),
    
        migrations.AddField(
            model_name='agentworkflowrun',
            name='user_context',
            field=models.TextField(blank=True, default=''),
        ),
    ]
