# Generated by Django 4.2.23 on 2026-05-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0014_agentsession_is_pinned_last_read_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentpendingexternalapproval',
            name='kind',
            field=models.CharField(help_text='Registry key, e.g. task, miro_board, calendar_event, forward_message.', max_length=64),
        ),
        migrations.AlterField(
            model_name='agentsession',
            name='approval_required',
            field=models.BooleanField(default=False, help_text='When true, external side effects require user approval before commit.'),
        ),
    ]
