# Generated by Django 4.2.23 on 2026-06-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0015_alter_agentpendingexternalapproval_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentworkflowrun',
            name='user_context',
            field=models.TextField(blank=True, default=''),
        ),
    ]
