# Generated by Django 4.2.23 on 2026-05-26 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_user_profile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0015_alter_agentpendingexternalapproval_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentWorkflowTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name, e.g. "Q4 Campaign Review"', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('review', 'Review'), ('optimization', 'Optimization'), ('analysis', 'Analysis'), ('reporting', 'Reporting'), ('other', 'Other')], default='other', help_text='Predefined category for organizing templates', max_length=20)),
                ('share_scope', models.CharField(choices=[('private', 'Private'), ('organization', 'Organization')], default='private', help_text='Visibility: private (creator only), organization (same org), public (all users)', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_workflow_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Required when share_scope=organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='core.organization')),
                ('workflow_definition', models.ForeignKey(help_text='Cloned workflow owned by this template', on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='agent.agentworkflowdefinition')),
            ],
            options={
                'db_table': 'agent_workflow_template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentProjectWorkflowBinding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_mode', models.CharField(choices=[('file_upload', 'File Upload'), ('analyze_action', 'Analyze Action'), ('message_keyword', 'Message Keyword')], help_text='How this workflow should be triggered', max_length=20)),
                ('trigger_keywords', models.JSONField(default=list, help_text='Keywords for message_keyword mode, e.g. ["analyze", "review"]')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority wins when multiple bindings match (same trigger_mode)')),
                ('is_default', models.BooleanField(default=False, help_text='Fallback template when no trigger conditions match (only one per project)')),
                ('is_active', models.BooleanField(default=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_bindings', to='core.project')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_bindings', to='agent.agentworkflowtemplate')),
            ],
            options={
                'db_table': 'agent_project_workflow_binding',
                'ordering': ['-priority', 'applied_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agentworkflowtemplate',
            index=models.Index(fields=['category', 'share_scope'], name='agent_workf_categor_b2b87d_idx'),
        ),
        migrations.AddIndex(
            model_name='agentworkflowtemplate',
            index=models.Index(fields=['organization', 'is_deleted'], name='agent_workf_organiz_8e0f27_idx'),
        ),
        migrations.AddIndex(
            model_name='agentworkflowtemplate',
            index=models.Index(fields=['created_by', 'is_deleted'], name='agent_workf_created_216d81_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentworkflowtemplate',
            constraint=models.CheckConstraint(check=models.Q(('organization__isnull', True), ('share_scope', 'organization'), _negated=True), name='agent_template_org_scope_needs_org'),
        ),
        migrations.AddIndex(
            model_name='agentprojectworkflowbinding',
            index=models.Index(fields=['project', 'is_active', 'priority'], name='agent_proje_project_06e9b8_idx'),
        ),
        migrations.AddIndex(
            model_name='agentprojectworkflowbinding',
            index=models.Index(fields=['project', 'is_default'], name='agent_proje_project_d84efa_idx'),
        ),
        migrations.AddIndex(
            model_name='agentprojectworkflowbinding',
            index=models.Index(fields=['trigger_mode'], name='agent_proje_trigger_c3fece_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentprojectworkflowbinding',
            unique_together={('project', 'template')},
        ),
    ]
