# Generated by Django 4.2.23 on 2026-06-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0016_agentworkflowrun_user_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentworkflowrun',
            name='user_context',
        ),
    ]
