# Generated by Django 4.2.23 on 2026-06-03 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_user_profile_fields'),
        ('agent', '0022_agentworkflowtemplate_use_cases'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentworkflowtemplate',
            new_name='agent_workf_categor_ac4dcd_idx',
            old_name='agent_tmpl_category_idx',
        ),
        migrations.AlterField(
            model_name='agentworkflowtemplate',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='If set, all members of this organization can see the template', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='core.organization'),
        ),
    ]
