# Generated by Django 4.2.23 on 2026-06-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0026_remove_bindings_and_input_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentworkflowtemplate',
            name='use_cases',
            field=models.JSONField(blank=True, default=list, help_text='Example scenarios / phrases describing when to use this template (documentation for users; not used for automatic routing).'),
        ),
    ]
