# Generated by Django 4.2.23 on 2026-06-05 23:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0028_merge_user_context_and_template_heads'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTriggerState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='trigger_state', serialize=False, to='agent.agentworkflowdefinition')),
                ('last_polling_check', models.DateTimeField(blank=True, null=True)),
                ('last_checked_data_hash', models.TextField(blank=True, default='', help_text='Hash of the data checked in last polling cycle (for deduplication)')),
                ('next_scheduled_run', models.DateTimeField(blank=True, help_text='Next scheduled execution time (computed from cron expression)', null=True)),
                ('last_successful_trigger', models.DateTimeField(blank=True, null=True)),
                ('last_trigger_type', models.CharField(blank=True, default='', max_length=20)),
                ('trigger_count_last_hour', models.IntegerField(default=0)),
                ('trigger_count_reset_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agent_workflow_trigger_state',
            },
        ),
        migrations.AddField(
            model_name='agentworkflowdefinition',
            name='trigger_config',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Trigger configuration JSON structure:\n        {\n            "trigger_type": "polling" | "instant" | "scheduled" | "manual",\n            "polling": {\n                "interval_minutes": 5 | 15 | 30 | 60,\n                "data_sources": ["spreadsheet", "task", "decision"],\n                "conditions": [{"type": "spreadsheet_upload", "project_id": 123}, ...]\n            },\n            "instant": {\n                "event_types": ["task.created", "task.status_changed", ...],\n                "webhook_enabled": true,\n                "webhook_secret": "auto_generated_uuid",\n                "filters": {"project_id": 123, "task_priority": ["HIGH", "CRITICAL"]}\n            },\n            "scheduled": {\n                "cron_expression": "0 9 * * 1",\n                "timezone": "UTC",\n                "enabled": true\n            },\n            "manual": {\n                "require_confirmation": true,\n                "allowed_users": [user_id_list] or "all"\n            }\n        }\n        '),
        ),
        migrations.AddField(
            model_name='agentworkflowdefinition',
            name='trigger_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic triggering for this workflow'),
        ),
        migrations.CreateModel(
            name='WorkflowTriggerLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('polling', 'Polling'), ('instant', 'Instant'), ('scheduled', 'Scheduled'), ('manual', 'Manual')], max_length=20)),
                ('status', models.CharField(choices=[('triggered', 'Triggered'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=20)),
                ('trigger_context', models.JSONField(default=dict, help_text='\n        Context about what caused the trigger:\n        {\n            "event_type": "task.status_changed",\n            "task_id": 456,\n            "old_status": "TODO",\n            "new_status": "DONE",\n            "spreadsheet_id": 789,\n            "webhook_source": "zapier",\n            "manual_user_id": 123\n        }\n        ')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_logs', to='agent.agentworkflowdefinition')),
                ('workflow_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trigger_log', to='agent.agentworkflowrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow', '-created_at'], name='agent_workf_workflo_907fe6_idx'), models.Index(fields=['trigger_type', 'status'], name='agent_workf_trigger_8f6f35_idx'), models.Index(fields=['created_at'], name='agent_workf_created_216ab0_idx')],
            },
        ),
    ]
