# Generated by Django 4.2.23 on 2026-06-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0029_workflowtriggerstate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentworkflowdefinition',
            name='trigger_enabled',
        ),
    ]
