# Generated by Django 4.2.23 on 2026-06-13 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0030_remove_trigger_enabled_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentworkflowtemplate',
            name='steps_config',
            field=models.JSONField(blank=True, default=list, help_text='Array of step configurations: [{"step_type": "...", "name": "...", "order": 0, "config": {...}}, ...]'),
        ),
        migrations.AlterField(
            model_name='agentworkflowtemplate',
            name='workflow_definition',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Legacy cloned workflow, being replaced by steps_config', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='agent.agentworkflowdefinition'),
        ),
    ]
