# Generated by Django 4.2.23 on 2026-06-13 07:48

from django.db import migrations


def migrate_template_steps(apps, schema_editor):
    """
    Migrate existing templates to use steps_config instead of workflow_definition.

    For each template:
    1. Get the workflow_definition's steps
    2. Copy them to steps_config
    3. Keep workflow_definition for now (will be removed in a later migration)
    """
    AgentWorkflowTemplate = apps.get_model('agent', 'AgentWorkflowTemplate')
    AgentWorkflowStep = apps.get_model('agent', 'AgentWorkflowStep')

    templates = AgentWorkflowTemplate.objects.filter(is_deleted=False)
    migrated_count = 0

    for template in templates:
        if template.workflow_definition_id:
            # Get all steps from the workflow_definition
            steps = AgentWorkflowStep.objects.filter(
                workflow_id=template.workflow_definition_id,
                is_deleted=False
            ).order_by('order')

            # Convert steps to config format
            steps_config = []
            for step in steps:
                steps_config.append({
                    'step_type': step.step_type,
                    'name': step.name,
                    'order': step.order,
                    'config': step.config or {},
                    'description': step.description or '',
                })

            # Save to steps_config
            template.steps_config = steps_config
            template.save(update_fields=['steps_config'])
            migrated_count += 1

    print(f"Migrated {migrated_count} templates to use steps_config")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - clear steps_config.
    Note: We don't recreate workflow_definitions as they still exist.
    """
    AgentWorkflowTemplate = apps.get_model('agent', 'AgentWorkflowTemplate')
    AgentWorkflowTemplate.objects.update(steps_config=[])
    print("Cleared steps_config from all templates")


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0031_add_template_steps_config'),
    ]

    operations = [
        migrations.RunPython(migrate_template_steps, reverse_migration),
    ]
