# Generated by Django 4.2.23 on 2026-06-14 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0017_remove_agentworkflowrun_user_context'),
        ('agent', '0033_merge_created_decisions_and_template_config'),
    ]

    operations = [
    ]
