# Generated by Django 4.2.23 on 2026-06-09 14:45

from django.db import migrations, models

from core.slug_backfill import backfill_slugs


def backfill(apps, schema_editor):
    backfill_slugs(apps.get_model('spreadsheet', 'Spreadsheet'), source_field='name')


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0009_alter_pivotconfig_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadsheet',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='spreadsheet',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
