# Generated by Django 4.2.23 on 2026-04-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_ads', '0001_initial'),
    ]

    operations = []
