# Generated by Django 4.2.23 on 2026-04-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_ads', '0002_metainsightdaily_comment_count_and_more'),
    ]

    operations = []
