# Generated by Django 4.2.23 on 2026-06-03 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '__first__'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name for this approval chain (e.g. 'Buyer → Lead → Client')", max_length=100)),
                ('task_type', models.CharField(blank=True, choices=[('budget', 'Budget'), ('asset', 'Asset'), ('retrospective', 'Retrospective'), ('report', 'Report'), ('execution', 'Execution'), ('scaling', 'Scaling'), ('alert', 'Alert'), ('experiment', 'Experiment'), ('optimization', 'Optimization'), ('communication', 'Client Communication'), ('platform_policy_update', 'Platform Policy Update')], help_text='Task type this chain applies to. Leave blank to apply to all task types.', max_length=50, null=True)),
                ('required_approvals', models.PositiveIntegerField(blank=True, help_text='Minimum number of approved ApprovalRecords required before the task can be locked. Defaults to total_steps (all steps must be approved) when null.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, help_text='Project this chain applies to. Leave blank to apply across all projects.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_chains', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(help_text='The title of the task', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, protected=True)),
                ('owner_invite_pending', models.BooleanField(default=False, help_text='True while the assigned owner has not yet accepted the task assignment.')),
                ('approver_invite_pending', models.BooleanField(default=False, help_text='True while the assigned approver has not yet accepted the approver assignment.')),
                ('current_approval_step', models.PositiveIntegerField(blank=True, help_text='Current step number in the approval chain (1-based). Null if no chain is assigned.', null=True)),
                ('due_date', models.DateField(blank=True, help_text='The due date of the task', null=True)),
                ('planned_start_date', models.DateField(blank=True, help_text='The planned start date of the task', null=True)),
                ('type', models.CharField(choices=[('budget', 'Budget'), ('asset', 'Asset'), ('retrospective', 'Retrospective'), ('report', 'Report'), ('execution', 'Execution'), ('scaling', 'Scaling'), ('alert', 'Alert'), ('experiment', 'Experiment'), ('optimization', 'Optimization'), ('communication', 'Client Communication'), ('platform_policy_update', 'Platform Policy Update')], help_text='Chosen type of the task', max_length=50)),
                ('priority', models.CharField(choices=[('HIGHEST', 'Highest'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('LOWEST', 'Lowest')], default='MEDIUM', help_text='Priority level of the task', max_length=20)),
                ('anomaly_status', models.CharField(default='NORMAL', help_text='Anomaly status for the task', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Task start date', null=True)),
                ('is_subtask', models.BooleanField(default=False, editable=False, help_text='Whether this task is a subtask. Once True, cannot be changed back.')),
                ('order_in_project', models.IntegerField(default=0, help_text='Order of task within its project')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Task creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Task last update timestamp')),
                ('revision_round', models.PositiveIntegerField(default=0, help_text='Tracks how many times this task has been resubmitted after rejection')),
                ('object_id', models.CharField(blank=True, help_text='Id of the linked model', max_length=255, null=True)),
                ('draft_payload', models.JSONField(blank=True, help_text='Draft form state captured from task create panel', null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Frontend-owned task tags [{name, color}, ...]')),
                ('linear_issue_id', models.CharField(blank=True, db_index=True, help_text='Linear issue UUID when this task was imported from Linear.', max_length=64, null=True)),
                ('approval_chain', models.ForeignKey(blank=True, help_text='The predefined approval chain assigned to this task (null = legacy single-approver mode)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='task.approvalchain')),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of the linked model', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who originally created the task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('current_approver', models.ForeignKey(help_text='The user who is currently reviewing the task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_to_approve', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='The user who owns the task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='The project that the task belongs to', on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_task', models.ForeignKey(help_text='Child task (subtask)', on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationship', to='task.task')),
                ('parent_task', models.ForeignKey(help_text='Parent task', on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='task.task')),
            ],
            options={
                'db_table': 'task_hierarchies',
            },
        ),
        migrations.CreateModel(
            name='TaskFieldHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=64)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_field_changes', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_history', to='task.task')),
            ],
            options={
                'db_table': 'task_field_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(help_text='Associated Task', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task.task')),
                ('user', models.ForeignKey(help_text='User who made the comment', on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Uploaded file', max_length=500, upload_to='task/attachments/%Y/%m/%d/')),
                ('original_filename', models.CharField(help_text='Original filename before upload', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100)),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 checksum of the file', max_length=64)),
                ('scan_status', django_fsm.FSMField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('clean', 'Clean'), ('infected', 'Infected'), ('error_scanning', 'Error Scanning')], default='pending', help_text='Virus scan status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(help_text='Associated Task', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='task.task')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the file', on_delete=django.db.models.deletion.CASCADE, related_name='task_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(help_text='Whether approved')),
                ('comment', models.TextField(blank=True, help_text='Reason for approval or rejection', null=True)),
                ('decided_time', models.DateTimeField(auto_now_add=True, help_text='Decision timestamp')),
                ('step_number', models.PositiveIntegerField(help_text='Approval step number')),
                ('revision_round', models.PositiveIntegerField(default=0, help_text='Revision round this approval record belongs to')),
                ('has_rejection_history', models.BooleanField(default=False, help_text='Whether this task had prior rejections at time of this record')),
                ('resubmitted_after_reject', models.BooleanField(default=False, help_text='Whether this record was created after a resubmission')),
                ('approved_by', models.ForeignKey(help_text='Approver user', on_delete=django.db.models.deletion.PROTECT, related_name='task_approval_records', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='Associated Task', on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='task.task')),
            ],
            options={
                'ordering': ['revision_round', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalChainStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Position of this step in the chain (1-based, e.g. 1 = Buyer, 2 = Lead, 3 = Client)')),
                ('approver', models.ForeignKey(help_text='User responsible for approving at this step', on_delete=django.db.models.deletion.CASCADE, related_name='approval_chain_steps', to=settings.AUTH_USER_MODEL)),
                ('chain', models.ForeignKey(help_text='The approval chain this step belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='task.approvalchain')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('causes', 'Causes'), ('blocks', 'Blocks'), ('clones', 'Clones'), ('relates_to', 'Relates To')], help_text='Type of relationship', max_length=20)),
                ('source_task', models.ForeignKey(help_text='Source task in the relationship', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='task.task')),
                ('target_task', models.ForeignKey(help_text='Target task in the relationship', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='task.task')),
            ],
            options={
                'db_table': 'task_relations',
                'indexes': [models.Index(fields=['source_task', 'relationship_type'], name='task_relati_source__6eff97_idx'), models.Index(fields=['target_task', 'relationship_type'], name='task_relati_target__05e002_idx')],
                'unique_together': {('source_task', 'target_task', 'relationship_type')},
            },
        ),
        migrations.CreateModel(
            name='TaskPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(help_text='Task pinned by the user', on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='task.task')),
                ('user', models.ForeignKey(help_text='User who pinned the task', on_delete=django.db.models.deletion.CASCADE, related_name='task_pins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'task'], name='taskpin_user_task_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='taskpin',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='taskpin_unique_task_user'),
        ),
        migrations.AddIndex(
            model_name='taskhierarchy',
            index=models.Index(fields=['parent_task'], name='task_hierar_parent__41f3ee_idx'),
        ),
        migrations.AddIndex(
            model_name='taskhierarchy',
            index=models.Index(fields=['child_task'], name='task_hierar_child_t_63e1b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskhierarchy',
            unique_together={('parent_task', 'child_task')},
        ),
        migrations.AddIndex(
            model_name='taskfieldhistory',
            index=models.Index(fields=['task', '-changed_at'], name='task_field_history_task_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('linear_issue_id__isnull', False)), fields=('project', 'linear_issue_id'), name='task_unique_linear_issue_per_project'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalrecord',
            unique_together={('task', 'step_number', 'revision_round')},
        ),
        migrations.AlterUniqueTogether(
            name='approvalchainstep',
            unique_together={('chain', 'order')},
        ),
    ]
