# Generated by Cursor on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_approvalchain_required_approvals"),
    ]

    operations = []

