# Generated by Django 4.2.23 on 2026-03-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_draft_payload'),
    ]

    operations = []
