# Generated by Django 4.2.23 on 2026-05-19 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_task_invite_pending'),
        ('task', '0010_taskfieldhistory'),
    ]

    operations = []
