# Generated by Django 4.2.23 on 2026-05-26 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_merge_invite_pending_and_taskpin'),
        ('task', '0014_merge_task_labels_and_pins'),
    ]

    operations = [
    ]
