# Generated by Django 4.2.23 on 2026-05-26 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_merge_20260527_0357'),
    ]

    operations = [
    ]
