# Generated by Django 4.2.23 on 2026-06-09 14:39

from django.db import migrations, models

from core.slug_backfill import backfill_slugs


def backfill(apps, schema_editor):
    backfill_slugs(apps.get_model('task', 'Task'), source_field='summary')


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_add_origin_action_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
