# Generated by Django 4.2.23 on 2026-04-26 05:51
# NOTE: This is a placeholder migration. The fields were already added in 0001_initial.py
# This migration exists only to maintain the dependency chain for other apps.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # Fields already exist in 0001_initial (password_reset_token, etc.)
    ]
