# Generated by Django 4.2.23 on 2026-05-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_user_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('CAMPAIGN', 'Campaign'), ('BUDGET_REQUEST', 'Budget Request'), ('BUDGET_POOL', 'Budget Pool'), ('BUDGET_ESCALATION', 'Budget Escalation'), ('QUEUE', 'Queue'), ('SUPPORT_TEAM', 'Support Team'), ('TICKET', 'Ticket'), ('INVITATION', 'Invitation')], max_length=20),
        ),
    ]
