# Generated by Django 4.2.23 on 2026-05-24 05:31
# NOTE: This is a placeholder migration. The field was already altered in 0001_initial.py
# This migration exists only to maintain the dependency chain for other apps.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_user_profile_fields'),
    ]

    operations = [
        # Permission.module choices already updated in 0001_initial
    ]
