# Generated by Django 4.2.23 on 2026-05-26 01:06
# NOTE: This is a placeholder migration. The field may already be in the correct state in 0001_initial.py
# This migration exists only to maintain the dependency chain for other apps.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_permission_module'),
    ]

    operations = [
        # Project.organization field state handled in 0001_initial or database
    ]
