# Generated by Django 4.2.23 on 2026-06-21 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_backfill_org_admin_fallback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='active_project',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The currently active project for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='core.project'),
        ),
    ]
