# Generated by Django 4.2.23 on 2026-06-24 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_organization',
            field=models.ForeignKey(blank=True, help_text='The organization context the user is currently viewing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use current_organization instead. Kept for backward compatibility.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, help_text='Specific email address (optional - if null, anyone can use the link)', max_length=254, null=True)),
                ('role', models.CharField(default='member', help_text="Role the invitee will receive: 'admin', 'member', 'viewer'", max_length=50)),
                ('token', models.CharField(help_text='Unique token for the invitation link', max_length=64, unique=True)),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='Maximum number of times this invitation can be used (0 = unlimited)')),
                ('use_count', models.PositiveIntegerField(default=0, help_text='Number of times this invitation has been used')),
                ('expires_at', models.DateTimeField(help_text='When the invitation expires')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this invitation is active (can be manually revoked)')),
                ('invited_by', models.ForeignKey(blank=True, help_text='User who created this invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_org_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization being invited to', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.CharField(default='member', help_text="Organization-level role: 'admin', 'member', 'viewer'", max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='When the user joined the organization')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this membership is currently active')),
                ('invited_by', models.ForeignKey(blank=True, help_text='User who invited this member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization the user belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.organization')),
                ('user', models.ForeignKey(help_text='User who is a member of the organization', on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='core_organi_user_id_3b5068_idx'), models.Index(fields=['organization', 'is_active'], name='core_organi_organiz_e09ef5_idx')],
                'unique_together': {('user', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationInvitationUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(auto_now_add=True, help_text='When the invitation was used')),
                ('invitation', models.ForeignKey(help_text='The invitation that was used', on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='core.organizationinvitation')),
                ('user', models.ForeignKey(help_text='User who used the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='invitation_uses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['invitation', 'used_at'], name='core_organi_invitat_4fabb0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='organizationinvitation',
            index=models.Index(fields=['token'], name='core_organi_token_cd3e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationinvitation',
            index=models.Index(fields=['organization', 'is_active'], name='core_organi_organiz_62f376_idx'),
        ),
    ]
