# Generated by Django 4.2.23 on 2026-06-29 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_migrate_organization_memberships'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('member_joined', 'Member Joined'), ('member_removed', 'Member Removed'), ('member_left', 'Member Left'), ('plan_subscribed', 'Plan Subscribed'), ('plan_changed', 'Plan Changed'), ('plan_cancel_scheduled', 'Plan Cancel Scheduled'), ('plan_reactivated', 'Plan Reactivated'), ('seats_changed', 'Seats Changed'), ('plan_cancelled', 'Plan Cancelled'), ('token_quota_warning', 'Token Quota Warning'), ('token_quota_exceeded', 'Token Quota Exceeded'), ('token_overage_started', 'Token Overage Started')], db_index=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra context: plan name, seat count, token threshold, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered the event (null = system/webhook)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_activity_actor', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='core.organization')),
                ('target_user', models.ForeignKey(blank=True, help_text='User affected by the event (for member events)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_activity_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='core_organi_organiz_f6450a_idx')],
            },
        ),
    ]
