# Generated by Django 4.2.23 on 2026-06-03 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeetingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_meeting_id', models.CharField(blank=True, db_index=True, default='', help_text='Zoom long meeting ID.', max_length=64)),
                ('zoom_uuid', models.CharField(blank=True, db_index=True, default='', help_text='Zoom meeting instance UUID (past-meeting APIs).', max_length=128)),
                ('meeting_status', models.CharField(choices=[('unknown', 'Unknown'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended')], default='unknown', max_length=32)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_participants_count', models.PositiveIntegerField(blank=True, null=True)),
                ('participant_raw_json', models.JSONField(blank=True, default=list)),
                ('participant_structured_json', models.JSONField(blank=True, default=list)),
                ('recording_status', models.CharField(choices=[('unknown', 'Unknown'), ('none', 'None'), ('processing', 'Processing'), ('available', 'Available'), ('deleted', 'Deleted')], default='unknown', max_length=32)),
                ('recording_urls_json', models.JSONField(blank=True, default=list)),
                ('recording_metadata_json', models.JSONField(blank=True, default=dict)),
                ('summary_status', models.CharField(choices=[('not_applicable', 'Not applicable'), ('pending', 'Pending'), ('available', 'Available'), ('failed', 'Failed')], default='not_applicable', max_length=32)),
                ('summary_text', models.TextField(blank=True, default='')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_state', models.CharField(choices=[('never', 'Never synced'), ('in_progress', 'In progress'), ('ok', 'OK'), ('partial', 'Partial'), ('error', 'Error')], default='never', max_length=32)),
                ('sync_error', models.TextField(blank=True, default='')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_meeting_data', to='meetings.meeting')),
                ('zoom_host_user', models.ForeignKey(blank=True, help_text='User whose Zoom OAuth credential owns this meeting (set when linking).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zoom_meeting_data_hosted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZoomCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_access_token', models.TextField(help_text='Encrypted short-lived OAuth access token.')),
                ('encrypted_refresh_token', models.TextField(help_text='Encrypted OAuth refresh token.')),
                ('token_expires_at', models.DateTimeField()),
                ('zoom_user_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_credential', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
