# Generated by Django 4.2.23 on 2026-04-10 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0007_merge_20260407_0521"),
        ("zoom_integration", "0002_encrypt_zoom_oauth_tokens"),
    ]

    operations = []
