# Generated by Django 4.2.23 on 2026-05-07 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebook_meta', '0002_adcreative_media_campaign'),
    ]

    operations = []
